flake: drop broken codex-cli the default.nix for this was removed, so this package is no longer functional:
% nix build .#packages.aarch64-darwin.codex-cli
error:
       … while calling the 'import' builtin
         at /nix/store/67mzwrmcffhiagq88zwnigb8npv6lxxv-source/flake.nix:28:21:
           27|         ];
           28|         codex-cli = import ./codex-cli {
             |                     ^
           29|           inherit pkgs monorepo-deps;

       error: opening file '/nix/store/67mzwrmcffhiagq88zwnigb8npv6lxxv-source/codex-cli/default.nix': No such file or directory

Signed-off-by: Jörg Thalheim <joerg@thalheim.io>